substitutions:
  device_name: a4-button
  friendly_name: a4 button
  #Secret YAML is used for next data:
  api_pw: !secret api_password
  ota_pw: !secret ota_password

esphome:
  name: ${device_name}
  on_boot:
    then:
      - switch.turn_on: led_sw
      - light.turn_on:
          id: led_1
          brightness: 60%
          red: 0
          green: 80%
          blue: 0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

switch:
  - platform: gpio
    id: led_sw
    pin: 
      number: GPIO5
      inverted: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO4
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "My Light"
    id: led_1

# Enable logging
logger:
  level: DEBUG
